### ISSUE TITLE
Research team development in UE

### ISSUE THREAD

**Issue by wrongserenity** [wrongserenity/shabash-studios-project#12]
1. Изучить как ведется параллельная разработка на UE (булпринты, код, заливка в гит)
2. Посмотреть как работает комбинация блупринтов и кода

**Comment by Karkusha23** [comment]
**Работа с гитом:**

Для работы с системами контроля версий, в частности, с гитом, в движке существует Source Control, который позволяет отслеживать все изменения внутри самого движка

Подробнее здесь: https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/SourceControl/InEditor/

По какой-то причине Source Control не отслеживает C++ классы, то есть файлы .cpp и .h, поэтому их придется отправлять отдельным коммитом через сам гитхаб

Для работы гита с движком советуют ставить Git LFS и отслеживать им ассеты и карты

На всякий случай оставлю тут подробные инструкции

**Чтобы создать репозиторий** (Для ПМа)

1. Установить git, git lfs и GitHub Desktop
2. Запустить git bash, выполнить команду "git lfs install"
3. В Unreal Engine зайти в File -> Submit to Source Control, выбрать Git, нажать Initialize project with Git и Accept Settings
4. В GitHub Desktop зайти в Add -> Add existing repository, указать путь, по которому лежит проект, выбрать Initialize LFS
5. В git bash выполнить команды 
cd "{Путь проекта}"
git lfs track ".uasset"
git lfs track ".umap"
6. Сделать коммит


**Чтобы клонировать репозиторий** (Для всех остальных)

1. Установить git, git lfs и GitHub Desktop 
2. Запустить git bash, выполнить команду "git lfs install"
3. В GitHub Desktop выбрать репозиторий, нажать clone, выбрать папку, нажать Initialize LFS
4. В Unreal Engine 4 открыть склонировавшийся проект, зайти в File -> Submit to Source Control, выбрать Git, нажать Accept Settings


Чтобы закоммитить в локальный репозиторий через движок, используем Source Control -> Submit to Souce Control на панели инструментов

**Comment by Karkusha23** [comment]
Есть также система Multi-Use Editing, который позволяет редактировать проект всей команде в реальном времени, но она в бете, и я не знаю, нужна ли она нам, учитывая, что нам все равно все коммитить в гит, и у нас есть Source Control
https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/MultiUserEditing/


**С++ и Блупринты**

Далее выжимка из этой статьи: https://dtf.ru/gamedev/57618-balans-c-i-blueprints-v-ue4

Особенности C++:
1. Для каждого созданного C++ класса в начале сцены автоматически создается дефолтный объект (поэтому лучше не загружать ассеты внутри конструктора класса)
2. C++ классы не подгружают свои зависимости, если это не требуется

Для блупринтов справедливо ровно обратное:
1. Блупринты подгружаются по мере надобностие
2. Блупринты подгружаются полностью и со всеми зависимостями

Не рекомендуют писать Tick'и в блупринтах, особенно если они будут вызываться большую часть сессии

Блупринты работают в 7-30 раз медленнее, чем C++

Обычно делают так - пишут всю логику в базовом классе на C++, от него наследуют блупринтовый класс, куда добавляют меши, материалы, эффекты, анимации, и какую-то высокоуровневую логику с использованием методов, написанных на C++, пусть наследник и будет единственным
