### ISSUE TITLE
Research videogame market and develop business plan

### ISSUE THREAD

**Issue by wrongserenity** [wrongserenity/shabash-studios-project#19]
Необходимо проанализировать текущий рынок видеоигр примерно нашего уровня. Определить следующие моменты:

1. Какая у нас ЦА?
2. Какое для них УТП?
3. Как решаем проблему доставки продукта? - как гарантируем что человек если захотел, то сможет взять его (например, цена, или в случае PG13 - почему мать разрешит взять эту игру?)
4. Как такие игры в целом продаются?
5. Какие системы монетизации использовались и какая из них подойдет нам?
6. Какие есть конкуренты и в чем у нас отличие?
7. Какую проблему потребителя мы решаем?

Для всех материалов нужно сохранить игры и статьи, на которые ссылаешься

**Comment by defuntitled** [comment]
https://miro.com/app/board/uXjVNVv-2Fw=/?share_link_id=251015157158
