### ISSUE TITLE
Develop design: enemies basic

### ISSUE THREAD

**Issue by wrongserenity** [wrongserenity/shabash-studios-project#29]
Дизайн поведения противников. 
Необходимо:
1. Изучить референсы (другие игры), понять как ии перемещается там. Очень работает метод декомпозиции, когда пытаешься каким либо образом сломать ии в игре - много деталей открывается.
2. Изучить статьи по работе ИИ в играх (больше про инди сектор - сложные системы с укрытиями и прочим не успеем реализовать)
3. Подготовить подробные описания механик
4. Отметить что должно быть вынесено как параметры

Какие механики:
1. Перемещение 
> a) скорость 
> b) повороты
> c) преодоление наклонных поверхностей

2. Навмеш - этот вопрос нужно изучать вместе с Ринатом на примере реализации в движке, свое мы не потянем
> a) как выбирается путь
> b) какие ограниченя для генерации
> c) вырезаем ли динамически навмеш под другими ИИ и игроком

3. Навлинки 
> a) генерируем или нет
> b) на какие высоты враги могут запрыгивать
> c) на какую дистанцию могут перепрыгивать пропасти
> d) с какой высоты максимально может быть спрыжка вниз и т.п.

4. Атаки - этот вопрос нужно изучать вместе с Ринатом на примере реализации в движке, свое мы не потянем
a) сколько длится замах
b) как показываем игроку
c) сколько длится окно урона
d) как его обозначаем
e) сколько враг возвращает оружие
f) как он поворачивается за игроком если он пытается обойти противника

**Comment by defuntitled** [comment]
https://grizzled-windscreen-ad7.notion.site/78bf383294d443b1a9232da8f7dfce4a?pvs=4
