### ISSUE TITLE
Design basic set of mechanics

### ISSUE THREAD

**Issue by wrongserenity** [wrongserenity/shabash-studios-project#3]
Необходимо расписать несколько вариантов хай-левел дизайна, которые подойдут для проекта, с учетом:
1. Интерес команды к жанру или типам механик
2. Простота реализации
3. Возможность разнообразия и пейсинга
4. Применимость адаптивной сложности

**Comment by wrongserenity** [comment]
дополнительно указать:

1. Трудоемкость создания механики (относительно других механик)
2. Как может применяться адаптивная сложность
3. Описать user story / описание игрового процесса (то что у игрока будет происходить)
4. Как работает камера (висит в одной точке над комнатой, или следит за игроком, от третьего лица или из-за спины, перспектива или без нее)
5. Управление (какие клавиши и как примерно будут использоваться - перемещение, атаки, действия и т.п.)
6. Возможности персонажа (доступные игроку механики)
7. Разбить механики на три категории (must have / nice to have / to be done)
8. Выбрать что из этого может стать Уникальным Торговым Предложением

**Comment by defuntitled** [comment]
https://grizzled-windscreen-ad7.notion.site/78bf383294d443b1a9232da8f7dfce4a?pvs=4
