### ISSUE TITLE
Develop design: Adaptive Difficulty

### ISSUE THREAD

**Issue by wrongserenity** [wrongserenity/shabash-studios-project#31]
Система адаптивной сложности. 
Необходимо:
1. Изучить референсы (посмотреть от чего и на что менялись параметры в других играх)
2. Изучить статьи с описанием адаптивных систем в играх
3. Описать детали работы системы
4. Отметить параметры, которые можно будет настраивать

**Comment by defuntitled** [comment]
https://grizzled-windscreen-ad7.notion.site/78bf383294d443b1a9232da8f7dfce4a?pvs=4
