### ISSUE TITLE
Завести объект для сбора информации из игры и применения параметров на основе этих данных

### ISSUE THREAD

**Issue by wrongserenity** [wrongserenity/shabash-studios-project#53]
Нужен объект, который:
1. Сможет переноситься между уровнями (аналог в Unity - don't destroy on load)
2. Будет иметь функции для апдейта своих параметров 
3. Будет хранить эти значения (например в виде словаря или структуры 
4. Будет иметь функции, которые могут глобально менять параметры других сущностей в нужный момент (запуск сцены)

Дополнительно изучить как можно сделать перезапуск уровня на смерти
и после этого перезапуска описанный объект должен сохранить свои данные и быть готовым применить к другим сущностям (противникам, игроку, параметрам уровня)

**Comment by defuntitled** [comment]
данные необходимые для сбора:
1) фоксировать локальные максимумы модификатора урона
2) при смерти игрока фиксировать его текущий модификатор урона
