### ISSUE TITLE
Prepare narrative concept

### ISSUE THREAD

**Issue by wrongserenity** [wrongserenity/shabash-studios-project#9]
Подготовить небольшой концепт истории. Дополнить следующей информацией:

1. Способы подать нарратив (например: записки, аудиологи, элементы окружения)
2. Сеттинг

**Comment by LizBW** [comment]
1. Главная тема - разработка мира

Будущее, 2300 год (допустим), технологии вышли на невероятный уровень и полностью охватили мир людей. Однако есть люди, чьи навыки и знания являются ценнейшим ресурсом, которые при этом подвергают опасности их носителя.

Той информации, которой обладают эти люди, нет на просторах сети. Для их добычи приходится идти на крайние меры.

Основа мира - мрачность, технологии захватили мир.

Лабиринт можно сделать белым/светлым, показать то, что он не из реальности.

1. Герои

ГГ - носитель тех самых редких знаний и навыков, которые передались ему от его наставника.

Возраст: 27-30 лет

Род деятельности: военный, служил в элитных войсках

Во время ходе тайной операции глубоко на вражеской территории, ГГ был объявлен в розыск и вскоре попал в засаду вражеских сил. В ходе схватки он сражался с непревзойденным мастерством, однако был окружен и захвачен в плен непримиримыми врагами.

Жажда секретного военного знания привела врагов к решению применить современные технологии, которые чаще всего использовались в видеоиграх. Совершенно безобидные технологии используются для выкачки информации. Однако это дало сбой и произошла полная оцифровка сознания.

1. Лор
- Описание предметов (лут + можно добавить не только предметы прокачки, но и чисто лорные, из серии предметы из жизни ГГ, которые давали бы подсказки к разгадке самого мира). Отсюда можно запихнуть предметы из прошлого (цепочку, амулет и тд).
- Смена комнат, т.е. цвет комнаты, текст на стенах, определённые картинки можно впихнуть + диалоги гг об увиденном - будут появляться в зависимости от осознания гг происходящего, в начале реже, пустые чисто для истории, в конце чаще уже с мобами + можно использовать, чтобы показать уязвимости в системе
- Сами предметы - допустим диски, флешки или типа того, которые можно будет воспроизвести в тех же комнатах отдыха (можно обыграть их происхождение, допустим кто-то пытается помочь гг извне, либо само сознание гг подкидывает такое). Делать такие предметы не бросающимися в глаза, в начале можно подбросить пару таких штук для захвата интереса, далее игрок сам захочет найти их
- Классика - записки, делать короткими, чтобы не перегружать игрока, больше для создания атмосферы
- Видения/ воспоминания - не всегда же игроку только биться с мобами и лутать. Тут два варианта: 1) стандарт - сон, отдых гг; 2) создать предмет, который будет появляться периодически (коснулся = воспоминания) , или некое существо, за которым будет следовать гг (та же история, коснулся/поймал = воспоминания), тут 2в1, можно и про гг рассказать и про сам предмет/существо.
- Можно было бы конечно сделать аудио дорожки (пример atomic heart), но это довольно муторно и время затратно, тем не менее все еще вариант.

**Comment by LizBW** [comment]
Почему не останавливают:
1. Время идет по-другому. Вполне вариант.
Допустим время идет слишком быстро. Как бы то ни было врагам нужно просматривать материалы прохождения гг всех заданий. Вполне разумно что они чисто физически не просмотрят все в необходимый срок.
Тогда поиск союзника извне придаст атмосферу трагичности и безысходности, ну и объяснит решение полного отключения системы 
2. Есть союзник извне, допустим ученый, который также находится в плену и должен следить за ходом действий в симуляции 
Как пример - первый железный человек. Старк в плену должен сделать оружие + есть ученый, такой же пленник Инсен, который понимает язык врагов и помогает Старку.
Для него Старк - возможность вырваться из плена и вернуться к семье. 
Эту ситуацию можно и у нас провернуть. И кстати это объяснит появление всяких записок и тд
